name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout-step
        uses: actions/checkout@v2

  Buld:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: build-step
        run: ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
    needs: Clone-down

  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: test-step
        run: ci/unit-test-app.sh
    needs: Clone-down
